### ISSUE TITLE
Is SyncContext.Current restored after executing this method?

### ISSUE THREAD

**Issue by AArnott** [ufcpp/ContextFreeTask#14]
From the README of this repo, it looks like the SyncContext is cleared, but not restored later. Could that cause malfunctions in the calling code that is not expecting SyncContext to be cleared?

**Comment by slang25** [comment]
You're right, however the README is misleading and doesn't match the code, the code actually always captures and re-sets the context after. I'll PR the README 👍

**Comment by ufcpp** [comment]
released package: https://www.nuget.org/packages/ContextFreeTasks/0.4.0
