### ISSUE TITLE
Step over (f10) in VS does not work as expected

### ISSUE THREAD

**Issue by davidroth** [ufcpp/ContextFreeTask#16]
Don't know if this can be fixed by you or it is a VS debugger issue. 

![image](https://user-images.githubusercontent.com/338856/34870478-79a6e8fe-f78a-11e7-8f89-1f53fd3b91f6.png)

If I press F10 on this line, the expected next debugger step would be line 26.
Unfortunately the debugger steps out and the debugger never breaks on line 26.

If you change the return type to `Task`, this works.

**Comment by AgentFire** [comment]
Works fine in 2017, **15.5.5**.

**Comment by davidroth** [comment]
Yep, working fine now in VS 2017 15.6.4
